### ISSUE TITLE
Make use of hardware watchdog

### ISSUE THREAD

**Issue by samuelsadok** [odriverobotics/ODrive#483] opened 2020-09-08 13:18 UTC
There may be rare bugs which leave the ODrive unresponsive (e.g. #476) and this prevent unattended 24/7 operation of the ODrive.
Of course we should try to fix such issues when we find them, but guaranteeing their absence is hardly possible.

Making use of the STM's IWDG, fed from the various communication interfaces would help here. Optionally we can connect the IWDG to the axes' software watchdogs.

**Comment by madcowswe** [comment] 2020-09-08 23:43
Duplicate of #159

**Closed as completed by madcowswe** 2020-09-08 23:43 UTC
