### ISSUE TITLE
Issues with Device Firmware Upgrade (DFU)

### ISSUE THREAD

**Issue by StrikeEagleCC** [odriverobotics/ODrive#179] opened 2018-06-21 00:52 UTC
EDIT by @madcowswe:
This issue has come to describe a collection of issues regarding DFU, with the following final error messages:
* `ValueError: The device has no langid`
* `RuntimeError: An error occured. Device Status: (0, 2, 0, 0)`
* `IndexError: array index out of range` (DfuDevice.py:67)

---
when running "odrivetool dfu" on unflashed v2.5 ODrive:

```
$ odrivetool dfu
ODrive control utility v0.4.0.post3
Waiting for ODrive...
Traceback (most recent call last):
  File "/home/ben/pyenvs/odrive/bin/odrivetool", line 141, in <module>
    odrive.dfu.launch_dfu(args, logger, app_shutdown_token)
  File "/home/ben/pyenvs/odrive/lib/python3.5/site-packages/odrive/dfu.py", line 450, in launch_dfu
    update_device(device, firmware, logger, cancellation_token)
  File "/home/ben/pyenvs/odrive/lib/python3.5/site-packages/odrive/dfu.py", line 257, in update_device
    serial_number = device.serial_number
  File "/home/ben/pyenvs/odrive/lib/python3.5/site-packages/usb/core.py", line 830, in serial_number
    self._serial_number = util.get_string(self, self.iSerialNumber)
  File "/home/ben/pyenvs/odrive/lib/python3.5/site-packages/usb/util.py", line 314, in get_string
    raise ValueError("The device has no langid")
ValueError: The device has no langid
```
New v3.5 ODrive board, not yet flashed with firmware.
Ubuntu 16.04
python 3.5.2
Let me know if there is anything else I can provide to be helpful.

**Comment by madcowswe** [comment] 2018-06-21 02:45
As far as I can tell, it seems that the bug is that the udev rules are not set for the STM32 DFU device (different vendor/product id than the main ODrive).
See: https://github.com/pyusb/pyusb/issues/139

Maybe we should include the dfu device in the udev rules we install with the pip package. @samuelsadok do you think that's a good idea?

**Comment by cculbreath** [comment] 2018-07-02 05:06
I'm seeing the same issue with Python 3.7.0rc1 running MacOS 10.14 (Mojave Beta, I know I'm asking for trouble running a beta OS). Is there a work around?

**Comment by madcowswe** [comment] 2018-07-02 06:04
As a workaround I think it may work to do `sudo odrivetool dfu`. Someone please confirm?

**Comment by cculbreath** [comment] 2018-07-02 08:45
Hasn't worked for me. And I set up on another computer using 10.13 (High Sierra) just to make sure that it wasn't the beta OS giving me trouble.

**Comment by cculbreath** [comment] 2018-07-02 08:48
I'm seeing the error intermittently; sometimes the firmware flashes and verifies ok. Sometimes I get the langid error above, and sometimes I see this:
```
Erasing... done            
Flashing... (sector 1/6)  
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/odrivetool", line 142, in <module>
    odrive.dfu.launch_dfu(args, logger, app_shutdown_token)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/odrive/dfu.py", line 450, in launch_dfu
    update_device(device, firmware, logger, cancellation_token)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/odrive/dfu.py", line 381, in update_device
    dfudev.write_sector(sector, data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/odrive/dfuse/DfuDevice.py", line 187, in write_sector
    raise RuntimeError("An error occured. Device Status: {!r}".format(status))
RuntimeError: An error occured. Device Status: (0, 2, 0, 0)
```

**Comment by cculbreath** [comment] 2018-07-02 18:54
I'm going to try my Ubuntu system and see if that works out.

**Comment by samuelsadok** [comment] 2018-07-24 09:35
I don't think it's a permission issue given that it's intermittent. It seems to me more like the device hasn't properly initialized the USB system by the time we fetch the serial number.

I have seen the langid issue too occasionally, but IIRC it occurred only when the device was powered up while already connected to a PC with odrivetool running. This would support the thesis that it has to do with a race condition at initialization.

Some things you can try (independently):
 1. Before [this line](https://github.com/madcowswe/ODrive/blob/master/tools/odrive/dfu.py#L257) insert `time.sleep(1)`
 2. Before the same line insert `device._langids = (1033,)` ([source](https://github.com/pyusb/pyusb/issues/139#issuecomment-241432511))
 3. Force the device into DFU mode using the DIP switch and power it up before connecting to the PC

@madcowswe For some reason unknown to me I never had to add udev rules for the DFU device, it worked by default. If there turn out to be actual permission issues yeah you can add the rules to the `setup_udev_rules` routine.

**Comment by martyman-au** [comment] 2018-08-12 10:45
I am seeing a slightly different problem trying to flash my new Odrives. It is the same as the one described by alonks on the forum.

* Windows 7
* Anaconda3  (Python 3.6.5)
* I have tried both with DFU switch set and not
* I have set the stm32 bootloader driver to libusb-win32 using zadiag
* Firmware: v0.4.1-dev (As received)
* Odrive: 3.5-48v

When trying to run odrivetool dfu I get the following result.

```
(base) C:\Users\martin>odrivetool dfu
ODrive control utility v0.4.1
Waiting for ODrive...
Found ODrive 375F36623137 (v3.5-48V) with firmware [unknown version] in DFU mode

Checking online for newest firmware... found v0.4.2
Downloading firmware v0.4.2...
The configuration cannot be backed up because the device is already in DFU mode.
 The configuration may be lost after updating. Do you want to continue anyway? [
Y/n] y
Erasing... (sector 0/6)
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\Anaconda3\Scripts\odrivetool in <module>()
    140         print_version()
    141         import odrive.dfu
--> 142         odrive.dfu.launch_dfu(args, logger, app_shutdown_token)
    143
    144     elif args.command == 'liveplotter':

~\Anaconda3\lib\site-packages\odrive\dfu.py in launch_dfu(args, logger, cancellation_token)
    448     firmware = FirmwareFromFile(args.file) if args.file else None
    449
--> 450     update_device(device, firmware, logger, cancellation_token)
    451
    452

~\Anaconda3\lib\site-packages\odrive\dfu.py in update_device(device, firmware, logger, cancellation_token)
    370         for i, (sector, data) in enumerate(touched_sectors):
    371             print("Erasing... (sector {}/{})  \r".format(i, len(touched_sectors)), end='', flush=True)
--> 372             dfudev.erase_sector(sector)
    373         print('Erasing... done            \r', end='', flush=True)
    374     finally:

~\Anaconda3\lib\site-packages\odrive\dfuse\DfuDevice.py in erase_sector(self, sector)
    166
    167     def erase_sector(self, sector):
--> 168         self.set_alternate_safe(sector['alt'])
    169         self.erase(sector['addr'])
    170         status = self.wait_while_state(DfuState.DFU_DOWNLOAD_BUSY, timeout=sector['len']/32)

~\Anaconda3\lib\site-packages\odrive\dfuse\DfuDevice.py in set_alternate_safe(self, alt)
    148     def set_alternate_safe(self, alt):
    149         self.set_alternate(alt)
--> 150         if self.get_state() == DfuState.DFU_ERROR:
    151             self.clear_status()
    152             self.wait_while_state(DfuState.DFU_ERROR)

~\Anaconda3\lib\site-packages\odrive\dfuse\DfuDevice.py in get_state(self)
     65
     66     def get_state(self):
---> 67         return self.control_msg(DFU_REQUEST_RECEIVE, DFU_GETSTATE, 0, 1)[0]
     68
     69     def abort(self):

IndexError: array index out of range
```

This seems to be failing at the firmware erase step, which is earlier than the errors seen above.

**Comment by dkraft** [comment] 2018-08-26 18:41
I'm on W10, anaconda and upgraded to 4.1 but cant get 4.2 on same setup..

```
(base) C:\Users\Alien>odrivetool dfu
ODrive control utility v0.4.1
Waiting for ODrive...
Found ODrive 366533793037 (v3.5-48V) with firmware v0.4.1-dev
Checking online for newest firmware... found v0.4.2
Downloading firmware v0.4.2...
Saving configuration to C:\Users\Alien\AppData\Local\Temp\odrive-config-366533793037.json...
The file C:\Users\Alien\AppData\Local\Temp\odrive-config-366533793037.json already exists. Do you want to override it? [Y/n]
Configuration saved.
Putting device 366533793037 into DFU mode...
---------------------------------------------------------------------------
USBError                                  Traceback (most recent call last)
C:\ProgramData\Anaconda3\lib\site-packages\fibre\usbbulk_transport.py in process_packet(self, usbBuffer)
     96     try:
---> 97       ret = self.epw.write(usbBuffer, 0)
     98       if self._was_damaged:

C:\ProgramData\Anaconda3\lib\site-packages\usb\core.py in write(self, data, timeout)
    386         """
--> 387         return self.device.write(self, data, timeout)
    388

C:\ProgramData\Anaconda3\lib\site-packages\usb\core.py in write(self, endpoint, data, timeout)
    947                 _interop.as_array(data),
--> 948                 self.__get_timeout(timeout)
    949             )

C:\ProgramData\Anaconda3\lib\site-packages\usb\backend\libusb0.py in bulk_write(self, dev_handle, ep, intf, data, timeout)
    532                             intf,
--> 533                             data, timeout)
    534

C:\ProgramData\Anaconda3\lib\site-packages\usb\backend\libusb0.py in __write(self, fn, dev_handle, ep, intf, data, timeout)
    615                         length,
--> 616                         timeout
    617                     )))

C:\ProgramData\Anaconda3\lib\site-packages\usb\backend\libusb0.py in _check(ret)
    430             return ret
--> 431     raise USBError(errmsg, ret)
    432

USBError: [Errno None] b'libusb0-dll:err [submit_async] submitting request failed, win error: The device does not recognize the command.\r\n'

During handling of the above exception, another exception occurred:

TimeoutError                              Traceback (most recent call last)
C:\ProgramData\Anaconda3\Scripts\odrivetool in <module>()
    140         print_version()
    141         import odrive.dfu
--> 142         odrive.dfu.launch_dfu(args, logger, app_shutdown_token)
    143
    144     elif args.command == 'liveplotter':

C:\ProgramData\Anaconda3\lib\site-packages\odrive\dfu.py in launch_dfu(args, logger, cancellation_token)
    448     firmware = FirmwareFromFile(args.file) if args.file else None
    449
--> 450     update_device(device, firmware, logger, cancellation_token)
    451
    452

C:\ProgramData\Anaconda3\lib\site-packages\odrive\dfu.py in update_device(device, firmware, logger, cancellation_token)
    347     if dfudev is None:
    348         find_odrive_cancellation_token = Event(cancellation_token)
--> 349         put_into_dfu_mode(device, find_odrive_cancellation_token)
    350         stm_device = find_device_in_dfu_mode(serial_number, cancellation_token)
    351         find_odrive_cancellation_token.set()

C:\ProgramData\Anaconda3\lib\site-packages\odrive\dfu.py in put_into_dfu_mode(device, cancellation_token)
    224     print("Putting device {} into DFU mode...".format(device.__channel__.usb_device.serial_number))
    225     try:
--> 226         device.enter_dfu_mode()
    227     except fibre.ChannelBrokenException:
    228         pass # this is expected because the device reboots

C:\ProgramData\Anaconda3\lib\site-packages\fibre\remote_object.py in __call__(self, *args)
    122         for i in range(len(args)):
    123             self._inputs[i].set_value(args[i])
--> 124         self._parent.__channel__.remote_endpoint_operation(self._trigger_id, None, True, 0)
    125         if len(self._outputs) > 0:
    126             return self._outputs[0].get_value()

C:\ProgramData\Anaconda3\lib\site-packages\fibre\protocol.py in remote_endpoint_operation(self, endpoint_id, input, expect_ack, output_length)
    294                     self._my_lock.acquire()
    295                     try:
--> 296                         self._output.process_packet(packet)
    297                     except ChannelDamagedException:
    298                         attempt += 1

C:\ProgramData\Anaconda3\lib\site-packages\fibre\usbbulk_transport.py in process_packet(self, usbBuffer)
    104         raise fibre.protocol.ChannelBrokenException()
    105       elif ex.errno is None or ex.errno == 60 or ex.errno == 110: # timeout
--> 106         raise TimeoutError()
    107       else:
    108         self._logger.debug("error in usbbulk_transport.py, process_packet")

TimeoutError:
```

**Comment by alexisdal** [comment] 2019-03-05 14:52
i can confirm that a freshly install ubuntu 18, with a freshly install odrive, i did experience the 
    raise ValueError("The device has no langid")
and 
sudo odrivetool dfu
=> did seem to have reflashed my odrive 3.5 (it was laying around here and did not correctly report its version so i wanted to reflash it)

```
user@E5540:~$ sudo apt update
Atteint:1 http://fr.archive.ubuntu.com/ubuntu bionic InRelease
Réception de:2 http://fr.archive.ubuntu.com/ubuntu bionic-updates InRelease [88,7 kB]
Réception de:3 http://security.ubuntu.com/ubuntu bionic-security InRelease [88,7 kB]
Réception de:4 http://fr.archive.ubuntu.com/ubuntu bionic-backports InRelease [74,6 kB]
Réception de:5 http://fr.archive.ubuntu.com/ubuntu bionic-updates/main i386 Packages [458 kB]
Réception de:6 http://fr.archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [532 kB]
Réception de:7 http://security.ubuntu.com/ubuntu bionic-security/main amd64 DEP-11 Metadata [204 B]
Réception de:8 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 DEP-11 Metadata [20,7 kB]
Réception de:9 http://security.ubuntu.com/ubuntu bionic-security/universe DEP-11 48x48 Icons [12,2 kB]
Réception de:10 http://security.ubuntu.com/ubuntu bionic-security/universe DEP-11 64x64 Icons [50,4 kB]
Réception de:11 http://fr.archive.ubuntu.com/ubuntu bionic-updates/main amd64 DEP-11 Metadata [278 kB]
Réception de:12 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 DEP-11 Metadata [2 464 B]
Réception de:13 http://fr.archive.ubuntu.com/ubuntu bionic-updates/main DEP-11 48x48 Icons [66,7 kB]
Réception de:14 http://fr.archive.ubuntu.com/ubuntu bionic-updates/main DEP-11 64x64 Icons [123 kB]
Réception de:15 http://fr.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [737 kB]
Réception de:16 http://fr.archive.ubuntu.com/ubuntu bionic-updates/universe i386 Packages [728 kB]
Réception de:17 http://fr.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 DEP-11 Metadata [202 kB]
Réception de:18 http://fr.archive.ubuntu.com/ubuntu bionic-updates/universe DEP-11 48x48 Icons [188 kB]
Réception de:19 http://fr.archive.ubuntu.com/ubuntu bionic-updates/universe DEP-11 64x64 Icons [355 kB]
Réception de:20 http://fr.archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 DEP-11 Metadata [2 468 B]
Réception de:21 http://fr.archive.ubuntu.com/ubuntu bionic-backports/universe amd64 DEP-11 Metadata [7 356 B]
4 015 ko réceptionnés en 2s (1 744 ko/s)                                     
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
72 paquets peuvent être mis à jour. Exécutez « apt list --upgradable » pour les voir.
user@E5540:~$ sudo pip3 install odrive
sudo: pip3 : commande introuvable
user@E5540:~$ sudo python3 -m pip install odrive
/usr/bin/python3: No module named pip
user@E5540:~$ python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
user@E5540:~$ python
Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
user@E5540:~$ python3 -m pip install odrive
/usr/bin/python3: No module named pip
user@E5540:~$ sudo apt install  pip~
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
E: Impossible de trouver le paquet pip~
user@E5540:~$ sudo apt install  pip3
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
E: Impossible de trouver le paquet pip3
user@E5540:~$ pip

La commande « pip » n'a pas été trouvée, mais peut être installée avec :

sudo apt install python-pip

user@E5540:~$ sudo apt install python3-pip
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
Les paquets supplémentaires suivants seront installés : 
  dh-python libpython3-dev libpython3.6-dev python-pip-whl python3-dev
  python3-setuptools python3-wheel python3.6-dev
Paquets suggérés :
  python-setuptools-doc
Les NOUVEAUX paquets suivants seront installés :
  dh-python libpython3-dev libpython3.6-dev python-pip-whl python3-dev
  python3-pip python3-setuptools python3-wheel python3.6-dev
0 mis à jour, 9 nouvellement installés, 0 à enlever et 72 non mis à jour.
Il est nécessaire de prendre 47,4 Mo dans les archives.
Après cette opération, 81,0 Mo d'espace disque supplémentaires seront utilisés.
Souhaitez-vous continuer ? [O/n] 
Réception de:1 http://fr.archive.ubuntu.com/ubuntu bionic/main amd64 dh-python all 3.20180325ubuntu2 [89,2 kB]
Réception de:2 http://fr.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libpython3.6-dev amd64 3.6.7-1~18.04 [44,8 MB]
Réception de:3 http://fr.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libpython3-dev amd64 3.6.7-1~18.04 [7 328 B]
Réception de:4 http://fr.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 python-pip-whl all 9.0.1-2.3~ubuntu1 [1 652 kB]
Réception de:5 http://fr.archive.ubuntu.com/ubuntu bionic-updates/main amd64 python3.6-dev amd64 3.6.7-1~18.04 [508 kB]
Réception de:6 http://fr.archive.ubuntu.com/ubuntu bionic-updates/main amd64 python3-dev amd64 3.6.7-1~18.04 [1 288 B]
Réception de:7 http://fr.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 python3-pip all 9.0.1-2.3~ubuntu1 [114 kB]
Réception de:8 http://fr.archive.ubuntu.com/ubuntu bionic/main amd64 python3-setuptools all 39.0.1-2 [248 kB]
Réception de:9 http://fr.archive.ubuntu.com/ubuntu bionic/universe amd64 python3-wheel all 0.30.0-0.2 [36,5 kB]
47,4 Mo réceptionnés en 24s (2 005 ko/s)                                       
Sélection du paquet dh-python précédemment désélectionné.
(Lecture de la base de données... 147508 fichiers et répertoires déjà installés.)
Préparation du dépaquetage de .../0-dh-python_3.20180325ubuntu2_all.deb ...
Dépaquetage de dh-python (3.20180325ubuntu2) ...
Sélection du paquet libpython3.6-dev:amd64 précédemment désélectionné.
Préparation du dépaquetage de .../1-libpython3.6-dev_3.6.7-1~18.04_amd64.deb ...
Dépaquetage de libpython3.6-dev:amd64 (3.6.7-1~18.04) ...
Sélection du paquet libpython3-dev:amd64 précédemment désélectionné.
Préparation du dépaquetage de .../2-libpython3-dev_3.6.7-1~18.04_amd64.deb ...
Dépaquetage de libpython3-dev:amd64 (3.6.7-1~18.04) ...
Sélection du paquet python-pip-whl précédemment désélectionné.
Préparation du dépaquetage de .../3-python-pip-whl_9.0.1-2.3~ubuntu1_all.deb ...
Dépaquetage de python-pip-whl (9.0.1-2.3~ubuntu1) ...
Sélection du paquet python3.6-dev précédemment désélectionné.
Préparation du dépaquetage de .../4-python3.6-dev_3.6.7-1~18.04_amd64.deb ...
Dépaquetage de python3.6-dev (3.6.7-1~18.04) ...
Sélection du paquet python3-dev précédemment désélectionné.
Préparation du dépaquetage de .../5-python3-dev_3.6.7-1~18.04_amd64.deb ...
Dépaquetage de python3-dev (3.6.7-1~18.04) ...
Sélection du paquet python3-pip précédemment désélectionné.
Préparation du dépaquetage de .../6-python3-pip_9.0.1-2.3~ubuntu1_all.deb ...
Dépaquetage de python3-pip (9.0.1-2.3~ubuntu1) ...
Sélection du paquet python3-setuptools précédemment désélectionné.
Préparation du dépaquetage de .../7-python3-setuptools_39.0.1-2_all.deb ...
Dépaquetage de python3-setuptools (39.0.1-2) ...
Sélection du paquet python3-wheel précédemment désélectionné.
Préparation du dépaquetage de .../8-python3-wheel_0.30.0-0.2_all.deb ...
Dépaquetage de python3-wheel (0.30.0-0.2) ...
Paramétrage de python-pip-whl (9.0.1-2.3~ubuntu1) ...
Paramétrage de python3-wheel (0.30.0-0.2) ...
Paramétrage de libpython3.6-dev:amd64 (3.6.7-1~18.04) ...
Paramétrage de python3-pip (9.0.1-2.3~ubuntu1) ...
Traitement des actions différées (« triggers ») pour man-db (2.8.3-2ubuntu0.1) ...
Paramétrage de python3-setuptools (39.0.1-2) ...
Paramétrage de python3.6-dev (3.6.7-1~18.04) ...
Paramétrage de dh-python (3.20180325ubuntu2) ...
Paramétrage de libpython3-dev:amd64 (3.6.7-1~18.04) ...
Paramétrage de python3-dev (3.6.7-1~18.04) ...
user@E5540:~$ sudo pip3 install odrive
The directory '/home/user/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/user/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting odrive
  Downloading https://files.pythonhosted.org/packages/43/42/fcc8a36932f82d0dd30236ba9956d8410932e890dbeb959fe4b66bcf1cef/odrive-0.4.8.tar.gz (43kB)
    100% |████████████████████████████████| 51kB 1.3MB/s 
Collecting IntelHex (from odrive)
  Downloading https://files.pythonhosted.org/packages/bf/77/bf670318b3db325c71e2ac6a90b7bcfdf9fc739b7cf6aebb31715721623e/intelhex-2.2.1-py2.py3-none-any.whl (50kB)
    100% |████████████████████████████████| 51kB 1.9MB/s 
Collecting PySerial (from odrive)
  Downloading https://files.pythonhosted.org/packages/0d/e4/2a744dd9e3be04a0c0907414e2a01a7c88bb3915cbe3c8cc06e209f59c30/pyserial-3.4-py2.py3-none-any.whl (193kB)
    100% |████████████████████████████████| 194kB 1.7MB/s 
Collecting PyUSB (from odrive)
  Downloading https://files.pythonhosted.org/packages/5f/34/2095e821c01225377dda4ebdbd53d8316d6abb243c9bee43d3888fa91dd6/pyusb-1.0.2.tar.gz (54kB)
    100% |████████████████████████████████| 61kB 3.0MB/s 
Collecting ipython (from odrive)
  Downloading https://files.pythonhosted.org/packages/14/3b/3fcf422a99a04ee493e6a4fc3014e3c8ff484a7feed238fef68bdc285085/ipython-7.3.0-py3-none-any.whl (768kB)
    100% |████████████████████████████████| 778kB 840kB/s 
Collecting matplotlib (from odrive)
  Downloading https://files.pythonhosted.org/packages/e9/69/f5e05f578585ed9935247be3788b374f90701296a70c8871bcd6d21edb00/matplotlib-3.0.3-cp36-cp36m-manylinux1_x86_64.whl (13.0MB)
    100% |████████████████████████████████| 13.0MB 76kB/s 
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from odrive)
Collecting pygments (from ipython->odrive)
  Downloading https://files.pythonhosted.org/packages/13/e5/6d710c9cf96c31ac82657bcfb441df328b22df8564d58d0c4cd62612674c/Pygments-2.3.1-py2.py3-none-any.whl (849kB)
    100% |████████████████████████████████| 849kB 779kB/s 
Requirement already satisfied: setuptools>=18.5 in /usr/lib/python3/dist-packages (from ipython->odrive)
Collecting pickleshare (from ipython->odrive)
  Downloading https://files.pythonhosted.org/packages/9a/41/220f49aaea88bc6fa6cba8d05ecf24676326156c23b991e80b3f2fc24c77/pickleshare-0.7.5-py2.py3-none-any.whl
Collecting prompt-toolkit<2.1.0,>=2.0.0 (from ipython->odrive)
  Downloading https://files.pythonhosted.org/packages/f7/a7/9b1dd14ef45345f186ef69d175bdd2491c40ab1dfa4b2b3e4352df719ed7/prompt_toolkit-2.0.9-py3-none-any.whl (337kB)
    100% |████████████████████████████████| 337kB 1.3MB/s 
Requirement already satisfied: pexpect; sys_platform != "win32" in /usr/lib/python3/dist-packages (from ipython->odrive)
Collecting jedi>=0.10 (from ipython->odrive)
  Downloading https://files.pythonhosted.org/packages/25/2b/1f188901be099d52d7b06f4d3b7cb9f8f09692c50697b139eaf6fa2928d8/jedi-0.13.3-py2.py3-none-any.whl (178kB)
    100% |████████████████████████████████| 184kB 1.8MB/s 
Collecting traitlets>=4.2 (from ipython->odrive)
  Downloading https://files.pythonhosted.org/packages/93/d6/abcb22de61d78e2fc3959c964628a5771e47e7cc60d53e9342e21ed6cc9a/traitlets-4.3.2-py2.py3-none-any.whl (74kB)
    100% |████████████████████████████████| 81kB 2.1MB/s 
Collecting backcall (from ipython->odrive)
  Downloading https://files.pythonhosted.org/packages/84/71/c8ca4f5bb1e08401b916c68003acf0a0655df935d74d93bf3f3364b310e0/backcall-0.1.0.tar.gz
Collecting decorator (from ipython->odrive)
  Downloading https://files.pythonhosted.org/packages/f1/cd/7c8240007e9716b14679bc217a1baefa4432aa30394f7e2ec40a52b1a708/decorator-4.3.2-py2.py3-none-any.whl
Collecting numpy>=1.10.0 (from matplotlib->odrive)
  Downloading https://files.pythonhosted.org/packages/35/d5/4f8410ac303e690144f0a0603c4b8fd3b986feb2749c435f7cdbb288f17e/numpy-1.16.2-cp36-cp36m-manylinux1_x86_64.whl (17.3MB)
    100% |████████████████████████████████| 17.3MB 56kB/s 
Collecting kiwisolver>=1.0.1 (from matplotlib->odrive)
  Downloading https://files.pythonhosted.org/packages/69/a7/88719d132b18300b4369fbffa741841cfd36d1e637e1990f27929945b538/kiwisolver-1.0.1-cp36-cp36m-manylinux1_x86_64.whl (949kB)
    100% |████████████████████████████████| 952kB 682kB/s 
Collecting cycler>=0.10 (from matplotlib->odrive)
  Downloading https://files.pythonhosted.org/packages/f7/d2/e07d3ebb2bd7af696440ce7e754c59dd546ffe1bbe732c8ab68b9c834e61/cycler-0.10.0-py2.py3-none-any.whl
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 (from matplotlib->odrive)
  Downloading https://files.pythonhosted.org/packages/de/0a/001be530836743d8be6c2d85069f46fecf84ac6c18c7f5fb8125ee11d854/pyparsing-2.3.1-py2.py3-none-any.whl (61kB)
    100% |████████████████████████████████| 71kB 1.1MB/s 
Collecting python-dateutil>=2.1 (from matplotlib->odrive)
  Downloading https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl (226kB)
    100% |████████████████████████████████| 235kB 1.6MB/s 
Collecting wcwidth (from prompt-toolkit<2.1.0,>=2.0.0->ipython->odrive)
  Downloading https://files.pythonhosted.org/packages/7e/9f/526a6947247599b084ee5232e4f9190a38f398d7300d866af3ab571a5bfe/wcwidth-0.1.7-py2.py3-none-any.whl
Requirement already satisfied: six>=1.9.0 in /usr/lib/python3/dist-packages (from prompt-toolkit<2.1.0,>=2.0.0->ipython->odrive)
Collecting parso>=0.3.0 (from jedi>=0.10->ipython->odrive)
  Downloading https://files.pythonhosted.org/packages/19/b1/522b2671cc6d134c9d3f5dfc0d02fee07cab848e908d03d2bffea78cca8f/parso-0.3.4-py2.py3-none-any.whl (93kB)
    100% |████████████████████████████████| 102kB 2.3MB/s 
Collecting ipython-genutils (from traitlets>=4.2->ipython->odrive)
  Downloading https://files.pythonhosted.org/packages/fa/bc/9bd3b5c2b4774d5f33b2d544f1460be9df7df2fe42f352135381c347c69a/ipython_genutils-0.2.0-py2.py3-none-any.whl
Installing collected packages: IntelHex, PySerial, PyUSB, pygments, pickleshare, wcwidth, prompt-toolkit, parso, jedi, decorator, ipython-genutils, traitlets, backcall, ipython, numpy, kiwisolver, cycler, pyparsing, python-dateutil, matplotlib, odrive
  Running setup.py install for PyUSB ... done
  Running setup.py install for backcall ... done
  Running setup.py install for odrive ... done
Successfully installed IntelHex-2.2.1 PySerial-3.4 PyUSB-1.0.2 backcall-0.1.0 cycler-0.10.0 decorator-4.3.2 ipython-7.3.0 ipython-genutils-0.2.0 jedi-0.13.3 kiwisolver-1.0.1 matplotlib-3.0.3 numpy-1.16.2 odrive-0.4.8 parso-0.3.4 pickleshare-0.7.5 prompt-toolkit-2.0.9 pygments-2.3.1 pyparsing-2.3.1 python-dateutil-2.8.0 traitlets-4.3.2 wcwidth-0.1.7
user@E5540:~$ odrivetool dfu
ODrive control utility v0.4.8
Waiting for ODrive...
Found ODrive 367033663037 (v3.5-48V) with firmware [unknown version]
Checking online for newest firmware... found v0.4.8
Downloading firmware v0.4.8...
Saving configuration to /tmp/odrive-config-367033663037.json...
Configuration saved.
Putting device 367033663037 into DFU mode...
Traceback (most recent call last):
  File "/usr/local/bin/odrivetool", line 142, in <module>
    odrive.dfu.launch_dfu(args, logger, app_shutdown_token)
  File "/usr/local/lib/python3.6/dist-packages/odrive/dfu.py", line 454, in launch_dfu
    update_device(device, firmware, logger, cancellation_token)
  File "/usr/local/lib/python3.6/dist-packages/odrive/dfu.py", line 351, in update_device
    stm_device = find_device_in_dfu_mode(serial_number, cancellation_token)
  File "/usr/local/lib/python3.6/dist-packages/odrive/dfu.py", line 241, in find_device_in_dfu_mode
    stm_device = usb.core.find(idVendor=0x0483, idProduct=0xdf11, **params)
  File "/usr/local/lib/python3.6/dist-packages/usb/core.py", line 1269, in find
    return _interop._next(device_iter(**args))
  File "/usr/local/lib/python3.6/dist-packages/usb/_interop.py", line 66, in _next
    return next(iter)
  File "/usr/local/lib/python3.6/dist-packages/usb/core.py", line 1249, in device_iter
    if _interop._all(tests) and (custom_match is None or custom_match(d)):
  File "/usr/local/lib/python3.6/dist-packages/usb/core.py", line 1248, in <genexpr>
    tests = (val == getattr(d, key) for key, val in kwargs.items())
  File "/usr/local/lib/python3.6/dist-packages/usb/core.py", line 830, in serial_number
    self._serial_number = util.get_string(self, self.iSerialNumber)
  File "/usr/local/lib/python3.6/dist-packages/usb/util.py", line 314, in get_string
    raise ValueError("The device has no langid")
ValueError: The device has no langid
user@E5540:~$ ^C
user@E5540:~$ sudo odrivetool dfu
ODrive control utility v0.4.8
Waiting for ODrive...
Found ODrive 367033663037 (v3.5-48V) with firmware [unknown version] in DFU mode
Checking online for newest firmware... found v0.4.8
Downloading firmware v0.4.8...
 The configuration may be lost after updating. Do you want to continue anyway? [Y/n] Y
Flashing... done            
Verifying... done            
Traceback (most recent call last):
  File "/usr/local/bin/odrivetool", line 142, in <module>
    odrive.dfu.launch_dfu(args, logger, app_shutdown_token)
  File "/usr/local/lib/python3.6/dist-packages/odrive/dfu.py", line 454, in launch_dfu
    update_device(device, firmware, logger, cancellation_token)
  File "/usr/local/lib/python3.6/dist-packages/odrive/dfu.py", line 417, in update_device
    if do_backup_config:
UnboundLocalError: local variable 'do_backup_config' referenced before assignment
user@E5540:~$ odrivetool
ODrive control utility v0.4.8
Please connect your ODrive.
You can also type help() or quit().

Connected to ODrive 367033663037 as odrv0
In [1]:                                                                         




```

**Comment by JustinOng** [comment] 2019-12-31 09:03
> As a workaround I think it may work to do `sudo odrivetool dfu`. Someone please confirm?

Can confirm this workaround works.

Was flashing a V3.6-24V with ODrive control utility v0.4.11 on Ubuntu 18 (Bionic).

**Comment by tombsar** [comment] 2020-08-27 02:47
I experienced both the ValueError and IndexError exceptions when trying to upgrade the firmware of an ODrive 3.6 24V with `odrivetool dfu` from Windows 10 (Anaconda). I tried everything mentioned in the docs (zadiag, dip switch, third-party dfu tool), but nothing I did got the board working until I moved to a Linux computer.

**Comment by madcowswe** [comment] 2020-08-29 23:41
The current plan to fix this for good is to write a custom bootloader so we don't have to worry about libusb and DfuSe not working well together. See #463.

**Comment by samuelsadok** [comment] 2020-08-31 11:28
It seems that `ValueError: The device has no langid` is after all related to missing permissions.

Adding
```
SUBSYSTEM=="usb", ATTR{idVendor}=="0483", ATTR{idProduct}=="df11", MODE="0666"
```
to `/etc/udev/rules.d/91-odrive.rules` fixes this issue.

I also pushed a fix for `IndexError: list index out of range` (discovery.py:179) here: 96cbe69f8aaabba669e39331e15ca364dd4e6eba. However this is not the same as the `IndexError` mentioned in the original post.

**Comment by Wetmelon** [comment] 2021-09-13 02:04
Fixed on Linux, MacOS, Wontfix on WIndows.  Recommend using STM32CubeProgrammer on Windows, `dfu-util` on Linux.

**Closed as completed by Wetmelon** 2021-09-13 02:04 UTC
